apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f3361q1xc-python-gitops
  description: This is GitOps manifest for f3361q1xc-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: f3361q1xc-python
    janus-idp.io/tekton: f3361q1xc-python 
    backstage.io/kubernetes-id: f3361q1xc-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f3361q1xc-python
