apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f3361q1xc-python
  janus-idp.io/tekton: f3361q1xc-python
  backstage.io/kubernetes-id: f3361q1xc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f3361q1xc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
